### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by George117** [RoHunter/PIC18F46K22#1]
- [x]  Rescrie functiile afisare cu parametrii

- [ ] Rescrie functiile buck/boost sa accepte procente pwm

- [ ] Stabileste relatiile matematice intre buck-boost

- [x] Elimina fisiere nefolosite(*.c, *.h)

- [x] Elimina cod mort

- [ ] Rescrie  toate functiile cu variabile globale --> tranferi parametrii

- [ ]  COMENTARII LA COD
